name: Static Site

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/485793403890/locations/global/workloadIdentityPools/serviceaccountidp/providers/github'
          service_account: 'serviceaccount@green-gearbox-418418.iam.gserviceaccount.com'

      # upload files to GCS
      # - id: 'upload-static-files'
      #   uses: 'google-github-actions/upload-cloud-storage@v1'
      #   with:
      #     path: 'public'
      #     destination: 'dansc0de'
      #     parent: false
